[workspace]
members = [
    "crates/lkit-cli",
    "crates/lkit-publish",
    "crates/lkit-repository",
    "crates/lkit-test-fixture",
]
default-members = ["crates/lkit-cli"]
resolver = "3"

[profile.dist]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
