[package]
name = "landscape-flare"
version.workspace = true
edition.workspace = true

[[bin]]
name = "lflare"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
crossterm = { workspace = true }
landscape-terrain-proto = { path = "../landscape-terrain-proto" }
ratatui = { workspace = true, features = ["crossterm_0_29"] }
rust-i18n = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "sync", "net", "io-util", "signal"] }
