[package]
name = "landscape-flare"
version.workspace = true
edition.workspace = true

[[bin]]
name = "lflare"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
landscape-terrain-proto = { path = "../landscape-terrain-proto" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "sync", "net", "io-util", "signal"] }
