[package]
name = "lkit-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lkit-core = { path = "../lkit-core" }
lkit-client = { path = "../lkit-client" }
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt", "time"] }
futures = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
tempfile = { workspace = true }
