[package]
name = "lkit-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lkit-core = { path = "../lkit-core" }
thiserror = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
tempfile = { workspace = true }
