[package]
name = "lkit-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lkit-core = { path = "../lkit-core" }
thiserror = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true, features = ["process", "fs", "io-util"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
tempfile = { workspace = true }
