use std::fs;
use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
use std::path::{Path, PathBuf};

use super::{ApplyReport, Family, MirrorError, MirrorName, backup_dir, paths};

fn mirror_host(mirror: MirrorName) -> &'static str {
    match mirror {
        MirrorName::Tuna => "mirrors.tuna.tsinghua.edu.cn",
        MirrorName::Aliyun => "mirrors.aliyun.com",
        MirrorName::Ustc => "mirrors.ustc.edu.cn",
        MirrorName::Official => "geo.mirror.pkgbuild.com",
    }
}

/// 生成新的 mirrorlist 内容：说明头 + 单个选中的 Server。
pub(crate) fn mirrorlist_content(mirror: MirrorName) -> String {
    format!(
        "# Generated by lkit set-mirror; previous mirrorlist is backed up under {}\nServer = https://{}/archlinux/$repo/os/$arch\n",
        paths().backup_root.display(),
        mirror_host(mirror)
    )
}

fn backup() -> Result<PathBuf, MirrorError> {
    let dir = backup_dir(Family::Arch);
    if dir.exists() {
        fs::remove_dir_all(&dir)?;
    }
    let target = dir.join("etc/pacman.d/mirrorlist");
    fs::create_dir_all(target.parent().expect("backup path has a parent"))?;
    fs::copy(&paths().pacman_mirrorlist, &target)?;
    Ok(dir)
}

/// 把 pacman mirrorlist 切换到指定镜像。写入失败时从备份回滚。
pub(crate) fn apply(mirror: MirrorName) -> Result<ApplyReport, MirrorError> {
    if !paths().pacman_mirrorlist.is_file() {
        return Err(MirrorError::Message(
            crate::tr!(crate::keys::mirror::MIRROR_NO_SOURCE_FILES).into(),
        ));
    }
    let backup_path = backup()?;
    if let Err(error) = write_atomic(&paths().pacman_mirrorlist, &mirrorlist_content(mirror)) {
        let _ = super::apt::rollback(&backup_path);
        return Err(error);
    }
    Ok(ApplyReport {
        changed_files: 1,
        skipped_repositories: 0,
        backup_path: Some(backup_path),
    })
}

/// 显示当前 mirrorlist 内容。
pub(crate) fn show() -> Result<String, MirrorError> {
    if !paths().pacman_mirrorlist.is_file() {
        return Err(MirrorError::Message(
            crate::tr!(crate::keys::mirror::MIRROR_NO_SOURCE_FILES).into(),
        ));
    }
    Ok(format!(
        "# {}\n{}",
        paths().pacman_mirrorlist.display(),
        fs::read_to_string(&paths().pacman_mirrorlist)?
    ))
}

/// 从备份恢复原 mirrorlist，成功后删除备份目录。
pub(crate) fn restore() -> Result<(), MirrorError> {
    let dir = backup_dir(Family::Arch);
    if !dir.exists() {
        return Err(MirrorError::Message(
            crate::tr!(crate::keys::mirror::MIRROR_NO_BACKUP).into(),
        ));
    }
    super::apt::restore_files(&dir, &paths().restore_root)?;
    fs::remove_dir_all(&dir)?;
    Ok(())
}

/// 原子写入：同目录临时文件 + rename，保留原文件权限位。
fn write_atomic(path: &Path, content: &str) -> Result<(), MirrorError> {
    let mode = fs::metadata(path)
        .map(|metadata| metadata.permissions().mode())
        .unwrap_or(0o644);
    let parent = path.parent().ok_or_else(|| {
        MirrorError::Message(format!("no parent directory for {}", path.display()))
    })?;
    let temp = parent.join(format!(".lkit-mirror-{}.tmp", std::process::id()));
    let mut options = fs::OpenOptions::new();
    options.write(true).create_new(true).mode(mode);
    let mut file = options.open(&temp)?;
    use std::io::Write;
    file.write_all(content.as_bytes())?;
    file.sync_all()?;
    drop(file);
    fs::rename(&temp, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_mirrorlist_for_each_mirror() {
        assert!(
            mirrorlist_content(MirrorName::Tuna)
                .contains("Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch")
        );
        assert!(
            mirrorlist_content(MirrorName::Aliyun)
                .contains("Server = https://mirrors.aliyun.com/archlinux/$repo/os/$arch")
        );
        assert!(
            mirrorlist_content(MirrorName::Ustc)
                .contains("Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch")
        );
        assert!(
            mirrorlist_content(MirrorName::Official)
                .contains("Server = https://geo.mirror.pkgbuild.com/archlinux/$repo/os/$arch")
        );
    }

    #[test]
    fn generated_mirrorlist_has_exactly_one_server() {
        for mirror in MirrorName::all() {
            let content = mirrorlist_content(mirror);
            assert_eq!(content.matches("Server = ").count(), 1);
            assert!(content.starts_with('#'));
        }
    }
}
