[package]
name = "lkit-publish"
version.workspace = true
edition.workspace = true

[[bin]]
name = "lkit-publish"
path = "src/main.rs"

[dependencies]
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
lkit-repository = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
url = { workspace = true }
zip = { workspace = true, features = ["deflate"] }
zstd = { workspace = true }
